### PR TITLE
Add german (de-de) translation

### PR DESCRIPTION
**Pull request by pascalpfeil**

### CODE REVIEW

**Comment by barnson** [comment]
Thanks! Can you add de-de.wxl to src/wixlib/iis.wixproj? That's needed to get the .wxl file in the extension.

**Comment by pascalpfeil** [comment]
Done @barnson :)

**Comment by GiantRabbit** [comment]
So... after 1 year still open?

**Comment by pascalpfeil** [comment]
Seems like it, sadly. But you can copy the files into your project to make them work if you want.

**Comment by barnson** [comment]
Would've been more polite to just ask if it fell through the cracks...

**Pull request merged**
